### PR TITLE
fixes #22 adopt to new endpoint and account structure of fixer.io

### LINKED ISSUE #22: Fixer API endpoint is dead
The currently implemented endpoint of fixer is down: https://api.fixer.io/latest
Neccessary changes are documented here: https://github.com/fixerAPI/fixer

Besides the new endpoint (API is unchanged otherwise) users now need to signup for an account and provide an api-key to access their rates api.

I am working on a fix for this lib, but it will break BC as for the mentioned api key (well, this lib is useless in it's current state, anyway).

### PR DESCRIPTION
**Pull request by jbrinksmeier**

### CODE REVIEW

**Comment by ojhaujjwal** [comment]
Thanks for your contribution.
Do you mind updating the README as well?

**Comment by jbrinksmeier** [comment]
Yes, that's neccessary indeed.
I think it would be best remove the default instantiation of the FixerProvider class in CurrencyConverter. Imo it should throw an exception if used without a configured provider set proactively. 
What do you think?

**Comment by ojhaujjwal** [comment]
I think we need to use another provider as a default provider like https://exchangeratesapi.io/

**Comment by jbrinksmeier** [comment]
yes, agreed. I hav not been aware of exchangerates.io. Will implement it as a default provider the ext days

**Comment by jbrinksmeier** [comment]
I implemented exchangeratesapi.io as suggested and made it the default provider, so current documentation works.

Please excuse the bad commit message, accidentally the last one has been cached and I just clicked it away to fast.

**Comment by ojhaujjwal** [comment]
Thank you very much for the contribution.
I have tagged a new release as well.

**Pull request merged**
